fix: don't do any replacement if DOCKER_IMAGE_TAG is empty

diff --git a/trigger-image-deploy/action.yml b/trigger-image-deploy/action.yml
--- a/trigger-image-deploy/action.yml
+++ b/trigger-image-deploy/action.yml
@@ -101,23 +101,26 @@ runs:
             FILE_ARGS+=(-f $TRIMMED_PATH)
           done
 
-          ##### Make sure "yq" package is installed first.
-          YQ_PACKAGE=yq
-          which $YQ_PACKAGE &> /dev/null
-          if [ ! $? -eq 0 ]; then
-            echo "Installing '$YQ_PACKAGE' (apt-get)..."
-            sudo apt-get install $YQ_PACKAGE &> /dev/null
-            if [ $? -eq 0 ]; then
-              echo "Successfully installed '$YQ_PACKAGE' (apt-get)."
-            else
-              echo "Package '$YQ_PACKAGE' not found (apt-get). Installing '$YQ_PACKAGE' (snap)..."
-              sudo snap install $YQ_PACKAGE &> /dev/null || exit 0
-              echo "Successfully installed '$YQ_PACKAGE' (snap)."
-            fi
-          fi
 
-          ##### Specify image tag in override file
-          yq e -i ".services.$DOCKER_SERVICE.image = \"ghcr.io/$REPO_NAME:$DOCKER_IMAGE_TAG\"" $OVERRIDE_FILE
+          if [ $DOCKER_IMAGE_TAG != "" ]; then
+            ##### Make sure "yq" package is installed first.
+            YQ_PACKAGE=yq
+            which $YQ_PACKAGE &> /dev/null
+            if [ ! $? -eq 0 ]; then
+              echo "Installing '$YQ_PACKAGE' (apt-get)..."
+              sudo apt-get install $YQ_PACKAGE &> /dev/null
+              if [ $? -eq 0 ]; then
+                echo "Successfully installed '$YQ_PACKAGE' (apt-get)."
+              else
+                echo "Package '$YQ_PACKAGE' not found (apt-get). Installing '$YQ_PACKAGE' (snap)..."
+                sudo snap install $YQ_PACKAGE &> /dev/null || exit 0
+                echo "Successfully installed '$YQ_PACKAGE' (snap)."
+              fi
+            fi
+
+            ##### Specify image tag in override file
+            yq e -i ".services.$DOCKER_SERVICE.image = \"ghcr.io/$REPO_NAME:$DOCKER_IMAGE_TAG\"" $OVERRIDE_FILE
+          fi
 
           ##### Append override file to docker-compose file args
           FILE_ARGS+=(-f $OVERRIDE_FILE)
